In [1]:
import sys,os
[sys.path.append(x[0]) for x in os.walk('tools')]
import dictionariesSL2P
import SL2P
from matplotlib import pyplot as plt
import os,numpy
import rasterio
import os
import pandas as pd

### Initiation

In [2]:
variableName='LAI'
imageCollectionName="LC08_T1L2"
fn='./testdata/Surface_refelctance_LC08_partition.csv'

#### Input data Control ***-
if variableName not in dictionariesSL2P.make_net_options().keys():
    raise ValueError(('Supported vegetation valiables: %s'%(dictionariesSL2P.make_net_options().keys())))
if imageCollectionName not in dictionariesSL2P.make_net_options()[variableName].keys():
    raise ValueError(('Supported EO datasets: %s'%(dictionariesSL2P.make_net_options()[variableName].keys())))  
       
sl2p_inputs_bands=dictionariesSL2P.make_net_options()[variableName][imageCollectionName]['inputBands']  
print ('SL2P input data format for %s data: %s' %(imageCollectionName,sl2p_inputs_bands))

SL2P input data format for LC08_T1L2 data: ['cosVZA', 'cosSZA', 'cosRAA', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7']

### 1- Read / prepare data

In [3]:
data=pd.read_csv(fn)
data

,Unnamed: 0,SR_B1,SR_B2,SR_B3,SR_B4,SR_B5,SR_B6,SR_B7,SR_QA_AEROSOL,ST_B10,...,date,longitude,latitude,cosVZA,cosSZA,cosRAA,partition,ID,PLOT_ID,Date
0,0,0.015187,0.018845,0.044007,0.030010,0.275228,0.149002,0.061745,96.0,45346.0,...,1.662743e+12,-95.190933,39.039824,0.9996,0.7868,0.0000,5.0,0,UKFS_047,9/9/2022
1,1,0.015407,0.019120,0.041423,0.028250,0.276933,0.145950,0.059902,96.0,45379.0,...,1.662743e+12,-95.190587,39.039830,0.9996,0.7868,0.0000,5.0,0,UKFS_047,9/9/2022
2,2,0.014170,0.018570,0.044090,0.030120,0.269535,0.149112,0.062762,66.0,45374.0,...,1.662743e+12,-95.190942,39.040094,0.9996,0.7868,0.0000,5.0,0,UKFS_047,9/9/2022
3,3,0.015297,0.019037,0.042742,0.028553,0.279023,0.146885,0.060370,96.0,45405.0,...,1.662743e+12,-95.190595,39.040100,0.9996,0.7868,0.0000,5.0,0,UKFS_047,9/9/2022
4,4,0.016865,0.020137,0.042825,0.028800,0.283423,0.151560,0.062570,96.0,45438.0,...,1.662743e+12,-95.190249,39.040107,0.9996,0.7868,0.0000,5.0,0,UKFS_047,9/9/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,1,0.028470,0.037847,0.065045,0.057098,0.282735,0.194213,0.098210,96.0,44650.0,...,1.530738e+12,-145.744736,63.879023,0.9987,0.7452,0.5164,1.0,194,DEJU_061,9/7/2018
1318,2,0.015215,0.021155,0.041313,0.031660,0.194130,0.125270,0.066145,96.0,44670.0,...,1.530738e+12,-145.745334,63.879298,0.9987,0.7452,0.5164,1.0,194,DEJU_061,9/7/2018
1319,3,0.024977,0.035070,0.061800,0.053742,0.269672,0.182993,0.091857,66.0,44638.0,...,1.530738e+12,-145.744724,63.879292,0.9987,0.7452,0.5164,1.0,194,DEJU_061,9/7/2018
1320,4,0.015215,0.021402,0.043568,0.034465,0.203838,0.128377,0.065732,96.0,44698.0,...,1.530738e+12,-145.745322,63.879567,0.9987,0.7452,0.5164,1.0,194,DEJU_061,9/7/2018
1321,5,0.020330,0.027067,0.052257,0.043265,0.234940,0.149222,0.073872,96.0,44680.0,...,1.530738e+12,-145.744712,63.879562,0.9987,0.7452,0.5164,1.0,194,DEJU_061,9/7/2018

### 2 - Run SL2PV0 / export outputs

In [4]:
DF=SL2P.SL2P(data,variableName,imageCollectionName,sl2p_inputs_bands)
DF

Estimating LAI from LC08_T1L2 data using SL2P-V0 [Marie Weiss]
Run SL2P...
SL2P start: 2024-05-08 15:45:59.544118
SL2P end: 2024-05-08 15:45:59.569018
Generating sl2p input data flag
Generating sl2p output product flag
Done

      estimateLAI  networkID  errorLAI  QC_input  QC_output
0        2.067529          0  0.818868         0          0
1        2.148030          0  0.829399         0          0
2        2.007088          0  0.806843         0          0
3        2.148009          0  0.831543         0          0
4        2.141221          0  0.828249         0          0
...           ...        ...       ...       ...        ...
1317     1.486875          0  0.700722         0          0
1318     1.483470          0  0.678867         0          0
1319     1.495866          0  0.709056         0          0
1320     1.528045          0  0.696356         0          0
1321     1.557654          0  0.723087         0          0

[1322 rows x 5 columns]

In [5]:
#Export DF
data[['date', 'longitude', 'latitude']].join(DF).to_csv(fn.replace('.csv','_%s_SL2P.csv'%(variableName)))

### 3 - Run SL2P-CCRS / export outputs

In [6]:
DF=SL2P.SL2PCCRS(data,variableName,imageCollectionName,sl2p_inputs_bands)
DF

Estimating LAI from LC08_T1L2 data using SL2P-CCRS
Run SL2P...
SL2P start: 2024-05-08 15:46:01.388741
SL2P end: 2024-05-08 15:46:01.389741
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.477842
SL2P end: 2024-05-08 15:46:01.478839
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.567038
SL2P end: 2024-05-08 15:46:01.568040
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.651038
SL2P end: 2024-05-08 15:46:01.652039
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.746206
SL2P end: 2024-05-08 15:46:01.747205
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.840311
SL2P end: 2024-05-08 15:46:01.841258
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.931207
SL2P end: 2024-05-08 15:46:01.933212
Generating sl2p input data flag
Generating sl2p output product flag
Done
Run SL2P...
SL2P start: 2024-05-08 15:46:01.960225
SL2P end: 2024-05-08 15:46:01.961223
Generating sl2p input data flag
Generating sl2p output product flag
Done

      estimateLAI  networkID  errorLAI  QC_input  QC_output  partition
0        1.864612          2  0.502005         0          0        5.0
1        1.941364          2  0.514068         0          0        5.0
2        1.794872          2  0.487092         0          0        5.0
3        1.947515          2  0.517712         0          0        5.0
4        1.952410          2  0.518357         0          0        5.0
...           ...        ...       ...       ...        ...        ...
1317     1.696923          3  0.503786         0          0        1.0
1318     1.444522          3  0.391697         0          0        1.0
1319     1.669413          3  0.490740         0          0        1.0
1320     1.516325          3  0.411912         0          0        1.0
1321     1.638706          3  0.459656         0          0        1.0

[1322 rows x 6 columns]

In [7]:
#Export DF
data[['date', 'longitude', 'latitude']].join(DF).to_csv(fn.replace('.csv','_%s_SL2PCCRS.csv'%(variableName)))